// Generated by https://github.com/juliettef/IconFontCppHeaders script GenerateIconFontCppHeaders.py
// for C and C++
// from font https://unpkg.com/lucide-static@latest/font/lucide.ttf
// Requires #include <stdint.h>

#pragma once

const unsigned int GetLucideIconsCompressedSize();
const uint32_t* GetLucideIconsCompressedData();
