
#pragma once

#include <bgfx/embedded_shader.h>

#undef BGFX_EMBEDDED_SHADER_DX9BC
#define BGFX_EMBEDDED_SHADER_DX9BC(...)
#undef BGFX_EMBEDDED_SHADER_PSSL
#define BGFX_EMBEDDED_SHADER_PSSL(...)
#undef BGFX_EMBEDDED_SHADER_ESSL
#define BGFX_EMBEDDED_SHADER_ESSL(...)
#undef BGFX_EMBEDDED_SHADER_GLSL
#define BGFX_EMBEDDED_SHADER_GLSL(...)
#undef BGFX_EMBEDDED_SHADER_METAL
#define BGFX_EMBEDDED_SHADER_METAL(...)
#undef BGFX_EMBEDDED_SHADER_NVN
#define BGFX_EMBEDDED_SHADER_NVN(...)
#undef BGFX_EMBEDDED_SHADER_SPIRV
#define BGFX_EMBEDDED_SHADER_SPIRV(...)
